version: '3'

services:
  smartclass-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartclass-frontend
    ports:
      - '80:80'
    environment:
      - API_BASE_URL=http://backend.smartclass.ubanillx.cn:8081/api
    restart: always
    networks:
      - smartclass-network

networks:
  smartclass-network:
    driver: bridge
