version: '3'

services:
  smartclass-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartclass-frontend
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - smartclass-network

networks:
  smartclass-network:
    driver: bridge
