/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Achievement } from './models/Achievement';
export type { AchievementDisplay } from './models/AchievementDisplay';
export type { AiAvatarAddRequest } from './models/AiAvatarAddRequest';
export type { AiAvatarChatRequest } from './models/AiAvatarChatRequest';
export type { AiAvatarChatVO } from './models/AiAvatarChatVO';
export type { AiAvatarQueryRequest } from './models/AiAvatarQueryRequest';
export type { AiAvatarUpdateRequest } from './models/AiAvatarUpdateRequest';
export type { AiAvatarVO } from './models/AiAvatarVO';
export type { Announcement } from './models/Announcement';
export type { AnnouncementAddRequest } from './models/AnnouncementAddRequest';
export type { AnnouncementQueryRequest } from './models/AnnouncementQueryRequest';
export type { AnnouncementUpdateRequest } from './models/AnnouncementUpdateRequest';
export type { BaseResponse_Achievement_ } from './models/BaseResponse_Achievement_';
export type { BaseResponse_AchievementDisplay_ } from './models/BaseResponse_AchievementDisplay_';
export type { BaseResponse_AiAvatarChatVO_ } from './models/BaseResponse_AiAvatarChatVO_';
export type { BaseResponse_AiAvatarVO_ } from './models/BaseResponse_AiAvatarVO_';
export type { BaseResponse_Announcement_ } from './models/BaseResponse_Announcement_';
export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_';
export type { BaseResponse_DailyArticleVO_ } from './models/BaseResponse_DailyArticleVO_';
export type { BaseResponse_DailyWordVO_ } from './models/BaseResponse_DailyWordVO_';
export type { BaseResponse_int_ } from './models/BaseResponse_int_';
export type { BaseResponse_IPage_Achievement_ } from './models/BaseResponse_IPage_Achievement_';
export type { BaseResponse_IPage_UserLearningRecord_ } from './models/BaseResponse_IPage_UserLearningRecord_';
export type { BaseResponse_List_Achievement_ } from './models/BaseResponse_List_Achievement_';
export type { BaseResponse_List_AchievementDisplay_ } from './models/BaseResponse_List_AchievementDisplay_';
export type { BaseResponse_List_AiAvatarVO_ } from './models/BaseResponse_List_AiAvatarVO_';
export type { BaseResponse_List_Announcement_ } from './models/BaseResponse_List_Announcement_';
export type { BaseResponse_List_DailyArticleVO_ } from './models/BaseResponse_List_DailyArticleVO_';
export type { BaseResponse_List_DailyWordVO_ } from './models/BaseResponse_List_DailyWordVO_';
export type { BaseResponse_List_string_ } from './models/BaseResponse_List_string_';
export type { BaseResponse_List_UserAchievement_ } from './models/BaseResponse_List_UserAchievement_';
export type { BaseResponse_List_UserLearningRecord_ } from './models/BaseResponse_List_UserLearningRecord_';
export type { BaseResponse_LoginUserVO_ } from './models/BaseResponse_LoginUserVO_';
export type { BaseResponse_long_ } from './models/BaseResponse_long_';
export type { BaseResponse_Page_AiAvatarChatVO_ } from './models/BaseResponse_Page_AiAvatarChatVO_';
export type { BaseResponse_Page_AiAvatarVO_ } from './models/BaseResponse_Page_AiAvatarVO_';
export type { BaseResponse_Page_Announcement_ } from './models/BaseResponse_Page_Announcement_';
export type { BaseResponse_Page_DailyArticleVO_ } from './models/BaseResponse_Page_DailyArticleVO_';
export type { BaseResponse_Page_DailyWordVO_ } from './models/BaseResponse_Page_DailyWordVO_';
export type { BaseResponse_Page_Post_ } from './models/BaseResponse_Page_Post_';
export type { BaseResponse_Page_PostVO_ } from './models/BaseResponse_Page_PostVO_';
export type { BaseResponse_Page_User_ } from './models/BaseResponse_Page_User_';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_';
export type { BaseResponse_PostVO_ } from './models/BaseResponse_PostVO_';
export type { BaseResponse_string_ } from './models/BaseResponse_string_';
export type { BaseResponse_User_ } from './models/BaseResponse_User_';
export type { BaseResponse_UserAchievement_ } from './models/BaseResponse_UserAchievement_';
export type { BaseResponse_UserDailyGoal_ } from './models/BaseResponse_UserDailyGoal_';
export type { BaseResponse_UserLearningRecord_ } from './models/BaseResponse_UserLearningRecord_';
export type { BaseResponse_UserLearningStats_ } from './models/BaseResponse_UserLearningStats_';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_';
export type { Course } from './models/Course';
export type { DailyArticleAddRequest } from './models/DailyArticleAddRequest';
export type { DailyArticleQueryRequest } from './models/DailyArticleQueryRequest';
export type { DailyArticleUpdateRequest } from './models/DailyArticleUpdateRequest';
export type { DailyArticleVO } from './models/DailyArticleVO';
export type { DailyWordAddRequest } from './models/DailyWordAddRequest';
export type { DailyWordQueryRequest } from './models/DailyWordQueryRequest';
export type { DailyWordUpdateRequest } from './models/DailyWordUpdateRequest';
export type { DailyWordVO } from './models/DailyWordVO';
export type { DeleteRequest } from './models/DeleteRequest';
export type { IPage_Achievement_ } from './models/IPage_Achievement_';
export type { IPage_Course_ } from './models/IPage_Course_';
export type { IPage_UserLearningRecord_ } from './models/IPage_UserLearningRecord_';
export type { LoginUserVO } from './models/LoginUserVO';
export type { OrderItem } from './models/OrderItem';
export type { Page_AiAvatarChatVO_ } from './models/Page_AiAvatarChatVO_';
export type { Page_AiAvatarVO_ } from './models/Page_AiAvatarVO_';
export type { Page_Announcement_ } from './models/Page_Announcement_';
export type { Page_DailyArticleVO_ } from './models/Page_DailyArticleVO_';
export type { Page_DailyWordVO_ } from './models/Page_DailyWordVO_';
export type { Page_Post_ } from './models/Page_Post_';
export type { Page_PostVO_ } from './models/Page_PostVO_';
export type { Page_User_ } from './models/Page_User_';
export type { Page_UserVO_ } from './models/Page_UserVO_';
export type { Post } from './models/Post';
export type { PostAddRequest } from './models/PostAddRequest';
export type { PostEditRequest } from './models/PostEditRequest';
export type { PostFavourAddRequest } from './models/PostFavourAddRequest';
export type { PostFavourQueryRequest } from './models/PostFavourQueryRequest';
export type { PostQueryRequest } from './models/PostQueryRequest';
export type { PostThumbAddRequest } from './models/PostThumbAddRequest';
export type { PostUpdateRequest } from './models/PostUpdateRequest';
export type { PostVO } from './models/PostVO';
export type { UploadFileRequest } from './models/UploadFileRequest';
export type { User } from './models/User';
export type { UserAchievement } from './models/UserAchievement';
export type { UserAddRequest } from './models/UserAddRequest';
export type { UserAiAvatarRequest } from './models/UserAiAvatarRequest';
export type { UserDailyGoal } from './models/UserDailyGoal';
export type { UserLearningRecord } from './models/UserLearningRecord';
export type { UserLearningStats } from './models/UserLearningStats';
export type { UserLoginByPhoneRequest } from './models/UserLoginByPhoneRequest';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserPhoneRegisterRequest } from './models/UserPhoneRegisterRequest';
export type { UserQueryRequest } from './models/UserQueryRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserUpdateMyRequest } from './models/UserUpdateMyRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { UserVO } from './models/UserVO';

export { AchievementControllerService } from './services/AchievementControllerService';
export { AiAvatarChatControllerService } from './services/AiAvatarChatControllerService';
export { AiAvatarControllerService } from './services/AiAvatarControllerService';
export { AnnouncementControllerService } from './services/AnnouncementControllerService';
export { CourseControllerService } from './services/CourseControllerService';
export { DailyArticleControllerService } from './services/DailyArticleControllerService';
export { DailyWordControllerService } from './services/DailyWordControllerService';
export { FileControllerService } from './services/FileControllerService';
export { PostControllerService } from './services/PostControllerService';
export { PostFavourControllerService } from './services/PostFavourControllerService';
export { PostThumbControllerService } from './services/PostThumbControllerService';
export { UserAiAvatarControllerService } from './services/UserAiAvatarControllerService';
export { UserControllerService } from './services/UserControllerService';
export { UserLearningControllerService } from './services/UserLearningControllerService';
export { WxMpControllerService } from './services/WxMpControllerService';
