/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError.ts';
export { CancelablePromise, CancelError } from './core/CancelablePromise.ts';
export { OpenAPI } from './core/OpenAPI.ts';
export type { OpenAPIConfig } from './core/OpenAPI.ts';

export type { Achievement } from './models/Achievement.ts';
export type { AchievementDisplay } from './models/AchievementDisplay.ts';
export type { AiAvatarAddRequest } from './models/AiAvatarAddRequest.ts';
export type { AiAvatarChatRequest } from './models/AiAvatarChatRequest.ts';
export type { AiAvatarChatVO } from './models/AiAvatarChatVO.ts';
export type { AiAvatarQueryRequest } from './models/AiAvatarQueryRequest.ts';
export type { AiAvatarUpdateRequest } from './models/AiAvatarUpdateRequest.ts';
export type { AiAvatarVO } from './models/AiAvatarVO.ts';
export type { Announcement } from './models/Announcement.ts';
export type { AnnouncementAddRequest } from './models/AnnouncementAddRequest.ts';
export type { AnnouncementQueryRequest } from './models/AnnouncementQueryRequest.ts';
export type { AnnouncementUpdateRequest } from './models/AnnouncementUpdateRequest.ts';
export type { BaseResponse_Achievement_ } from './models/BaseResponse_Achievement_.ts';
export type { BaseResponse_AchievementDisplay_ } from './models/BaseResponse_AchievementDisplay_.ts';
export type { BaseResponse_AiAvatarChatVO_ } from './models/BaseResponse_AiAvatarChatVO_.ts';
export type { BaseResponse_AiAvatarVO_ } from './models/BaseResponse_AiAvatarVO_.ts';
export type { BaseResponse_Announcement_ } from './models/BaseResponse_Announcement_.ts';
export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_.ts';
export type { BaseResponse_DailyArticleVO_ } from './models/BaseResponse_DailyArticleVO_.ts';
export type { BaseResponse_DailyWordVO_ } from './models/BaseResponse_DailyWordVO_.ts';
export type { BaseResponse_int_ } from './models/BaseResponse_int_.ts';
export type { BaseResponse_IPage_Achievement_ } from './models/BaseResponse_IPage_Achievement_.ts';
export type { BaseResponse_IPage_UserLearningRecord_ } from './models/BaseResponse_IPage_UserLearningRecord_.ts';
export type { BaseResponse_List_Achievement_ } from './models/BaseResponse_List_Achievement_.ts';
export type { BaseResponse_List_AchievementDisplay_ } from './models/BaseResponse_List_AchievementDisplay_.ts';
export type { BaseResponse_List_AiAvatarVO_ } from './models/BaseResponse_List_AiAvatarVO_.ts';
export type { BaseResponse_List_Announcement_ } from './models/BaseResponse_List_Announcement_.ts';
export type { BaseResponse_List_DailyArticleVO_ } from './models/BaseResponse_List_DailyArticleVO_.ts';
export type { BaseResponse_List_DailyWordVO_ } from './models/BaseResponse_List_DailyWordVO_.ts';
export type { BaseResponse_List_string_ } from './models/BaseResponse_List_string_.ts';
export type { BaseResponse_List_UserAchievement_ } from './models/BaseResponse_List_UserAchievement_.ts';
export type { BaseResponse_List_UserLearningRecord_ } from './models/BaseResponse_List_UserLearningRecord_.ts';
export type { BaseResponse_LoginUserVO_ } from './models/BaseResponse_LoginUserVO_.ts';
export type { BaseResponse_long_ } from './models/BaseResponse_long_.ts';
export type { BaseResponse_Page_AiAvatarChatVO_ } from './models/BaseResponse_Page_AiAvatarChatVO_.ts';
export type { BaseResponse_Page_AiAvatarVO_ } from './models/BaseResponse_Page_AiAvatarVO_.ts';
export type { BaseResponse_Page_Announcement_ } from './models/BaseResponse_Page_Announcement_.ts';
export type { BaseResponse_Page_DailyArticleVO_ } from './models/BaseResponse_Page_DailyArticleVO_.ts';
export type { BaseResponse_Page_DailyWordVO_ } from './models/BaseResponse_Page_DailyWordVO_.ts';
export type { BaseResponse_Page_Post_ } from './models/BaseResponse_Page_Post_.ts';
export type { BaseResponse_Page_PostVO_ } from './models/BaseResponse_Page_PostVO_.ts';
export type { BaseResponse_Page_User_ } from './models/BaseResponse_Page_User_.ts';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_.ts';
export type { BaseResponse_PostVO_ } from './models/BaseResponse_PostVO_.ts';
export type { BaseResponse_string_ } from './models/BaseResponse_string_.ts';
export type { BaseResponse_User_ } from './models/BaseResponse_User_.ts';
export type { BaseResponse_UserAchievement_ } from './models/BaseResponse_UserAchievement_.ts';
export type { BaseResponse_UserDailyGoal_ } from './models/BaseResponse_UserDailyGoal_.ts';
export type { BaseResponse_UserLearningRecord_ } from './models/BaseResponse_UserLearningRecord_.ts';
export type { BaseResponse_UserLearningStats_ } from './models/BaseResponse_UserLearningStats_.ts';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_.ts';
export type { Course } from './models/Course.ts';
export type { DailyArticleAddRequest } from './models/DailyArticleAddRequest.ts';
export type { DailyArticleQueryRequest } from './models/DailyArticleQueryRequest.ts';
export type { DailyArticleUpdateRequest } from './models/DailyArticleUpdateRequest.ts';
export type { DailyArticleVO } from './models/DailyArticleVO.ts';
export type { DailyWordAddRequest } from './models/DailyWordAddRequest.ts';
export type { DailyWordQueryRequest } from './models/DailyWordQueryRequest.ts';
export type { DailyWordUpdateRequest } from './models/DailyWordUpdateRequest.ts';
export type { DailyWordVO } from './models/DailyWordVO.ts';
export type { DeleteRequest } from './models/DeleteRequest.ts';
export type { IPage_Achievement_ } from './models/IPage_Achievement_.ts';
export type { IPage_Course_ } from './models/IPage_Course_.ts';
export type { IPage_UserLearningRecord_ } from './models/IPage_UserLearningRecord_.ts';
export type { LoginUserVO } from './models/LoginUserVO.ts';
export type { OrderItem } from './models/OrderItem.ts';
export type { Page_AiAvatarChatVO_ } from './models/Page_AiAvatarChatVO_.ts';
export type { Page_AiAvatarVO_ } from './models/Page_AiAvatarVO_.ts';
export type { Page_Announcement_ } from './models/Page_Announcement_.ts';
export type { Page_DailyArticleVO_ } from './models/Page_DailyArticleVO_.ts';
export type { Page_DailyWordVO_ } from './models/Page_DailyWordVO_.ts';
export type { Page_Post_ } from './models/Page_Post_.ts';
export type { Page_PostVO_ } from './models/Page_PostVO_.ts';
export type { Page_User_ } from './models/Page_User_.ts';
export type { Page_UserVO_ } from './models/Page_UserVO_.ts';
export type { Post } from './models/Post.ts';
export type { PostAddRequest } from './models/PostAddRequest.ts';
export type { PostEditRequest } from './models/PostEditRequest.ts';
export type { PostFavourAddRequest } from './models/PostFavourAddRequest.ts';
export type { PostFavourQueryRequest } from './models/PostFavourQueryRequest.ts';
export type { PostQueryRequest } from './models/PostQueryRequest.ts';
export type { PostThumbAddRequest } from './models/PostThumbAddRequest.ts';
export type { PostUpdateRequest } from './models/PostUpdateRequest.ts';
export type { PostVO } from './models/PostVO.ts';
export type { UploadFileRequest } from './models/UploadFileRequest.ts';
export type { User } from './models/User.ts';
export type { UserAchievement } from './models/UserAchievement.ts';
export type { UserAddRequest } from './models/UserAddRequest.ts';
export type { UserAiAvatarRequest } from './models/UserAiAvatarRequest.ts';
export type { UserDailyGoal } from './models/UserDailyGoal.ts';
export type { UserLearningRecord } from './models/UserLearningRecord.ts';
export type { UserLearningStats } from './models/UserLearningStats.ts';
export type { UserLoginByPhoneRequest } from './models/UserLoginByPhoneRequest.ts';
export type { UserLoginRequest } from './models/UserLoginRequest.ts';
export type { UserPhoneRegisterRequest } from './models/UserPhoneRegisterRequest.ts';
export type { UserQueryRequest } from './models/UserQueryRequest.ts';
export type { UserRegisterRequest } from './models/UserRegisterRequest.ts';
export type { UserUpdateMyRequest } from './models/UserUpdateMyRequest.ts';
export type { UserUpdateRequest } from './models/UserUpdateRequest.ts';
export type { UserVO } from './models/UserVO.ts';

export { AchievementControllerService } from './services/AchievementControllerService.ts';
export { AiAvatarChatControllerService } from './services/AiAvatarChatControllerService.ts';
export { AiAvatarControllerService } from './services/AiAvatarControllerService.ts';
export { AnnouncementControllerService } from './services/AnnouncementControllerService.ts';
export { CourseControllerService } from './services/CourseControllerService.ts';
export { DailyArticleControllerService } from './services/DailyArticleControllerService.ts';
export { DailyWordControllerService } from './services/DailyWordControllerService.ts';
export { FileControllerService } from './services/FileControllerService.ts';
export { PostControllerService } from './services/PostControllerService.ts';
export { PostFavourControllerService } from './services/PostFavourControllerService.ts';
export { PostThumbControllerService } from './services/PostThumbControllerService.ts';
export { UserAiAvatarControllerService } from './services/UserAiAvatarControllerService.ts';
export { UserControllerService } from './services/UserControllerService.ts';
export { UserLearningControllerService } from './services/UserLearningControllerService.ts';
export { WxMpControllerService } from './services/WxMpControllerService.ts';
