/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError.ts';
export { CancelablePromise, CancelError } from './core/CancelablePromise.ts';
export { OpenAPI } from './core/OpenAPI.ts';
export type { OpenAPIConfig } from './core/OpenAPI.ts';

export type { AiAvatarAddRequest } from './models/AiAvatarAddRequest.ts';
export type { AiAvatarBriefVO } from './models/AiAvatarBriefVO.ts';
export type { AiAvatarUpdateRequest } from './models/AiAvatarUpdateRequest.ts';
export type { AiAvatarVO } from './models/AiAvatarVO.ts';
export type { Announcement } from './models/Announcement.ts';
export type { AnnouncementAddRequest } from './models/AnnouncementAddRequest.ts';
export type { AnnouncementQueryRequest } from './models/AnnouncementQueryRequest.ts';
export type { AnnouncementUpdateRequest } from './models/AnnouncementUpdateRequest.ts';
export type { AnnouncementVO } from './models/AnnouncementVO.ts';
export type { BaseResponse_AiAvatarVO_ } from './models/BaseResponse_AiAvatarVO_.ts';
export type { BaseResponse_AnnouncementVO_ } from './models/BaseResponse_AnnouncementVO_.ts';
export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_.ts';
export type { BaseResponse_ChatMessageVO_ } from './models/BaseResponse_ChatMessageVO_.ts';
export type { BaseResponse_Course_ } from './models/BaseResponse_Course_.ts';
export type { BaseResponse_CourseCategory_ } from './models/BaseResponse_CourseCategory_.ts';
export type { BaseResponse_CourseChapter_ } from './models/BaseResponse_CourseChapter_.ts';
export type { BaseResponse_CourseMaterial_ } from './models/BaseResponse_CourseMaterial_.ts';
export type { BaseResponse_CourseReviewVO_ } from './models/BaseResponse_CourseReviewVO_.ts';
export type { BaseResponse_CourseSection_ } from './models/BaseResponse_CourseSection_.ts';
export type { BaseResponse_CourseVO_ } from './models/BaseResponse_CourseVO_.ts';
export type { BaseResponse_DailyArticleVO_ } from './models/BaseResponse_DailyArticleVO_.ts';
export type { BaseResponse_DailyWordVO_ } from './models/BaseResponse_DailyWordVO_.ts';
export type { BaseResponse_int_ } from './models/BaseResponse_int_.ts';
export type { BaseResponse_List_AiAvatarBriefVO_ } from './models/BaseResponse_List_AiAvatarBriefVO_.ts';
export type { BaseResponse_List_AiAvatarVO_ } from './models/BaseResponse_List_AiAvatarVO_.ts';
export type { BaseResponse_List_ChatMessageVO_ } from './models/BaseResponse_List_ChatMessageVO_.ts';
export type { BaseResponse_List_ChatSessionVO_ } from './models/BaseResponse_List_ChatSessionVO_.ts';
export type { BaseResponse_List_Course_ } from './models/BaseResponse_List_Course_.ts';
export type { BaseResponse_List_CourseCategory_ } from './models/BaseResponse_List_CourseCategory_.ts';
export type { BaseResponse_List_CourseChapter_ } from './models/BaseResponse_List_CourseChapter_.ts';
export type { BaseResponse_List_CourseMaterial_ } from './models/BaseResponse_List_CourseMaterial_.ts';
export type { BaseResponse_List_CourseSection_ } from './models/BaseResponse_List_CourseSection_.ts';
export type { BaseResponse_List_CourseVO_ } from './models/BaseResponse_List_CourseVO_.ts';
export type { BaseResponse_List_DailyArticleVO_ } from './models/BaseResponse_List_DailyArticleVO_.ts';
export type { BaseResponse_List_DailyWordVO_ } from './models/BaseResponse_List_DailyWordVO_.ts';
export type { BaseResponse_List_long_ } from './models/BaseResponse_List_long_.ts';
export type { BaseResponse_List_Map_string_object_ } from './models/BaseResponse_List_Map_string_object_.ts';
export type { BaseResponse_List_TeacherVO_ } from './models/BaseResponse_List_TeacherVO_.ts';
export type { BaseResponse_List_UserAiAvatarVO_ } from './models/BaseResponse_List_UserAiAvatarVO_.ts';
export type { BaseResponse_List_UserLevelVO_ } from './models/BaseResponse_List_UserLevelVO_.ts';
export type { BaseResponse_LoginUserVO_ } from './models/BaseResponse_LoginUserVO_.ts';
export type { BaseResponse_long_ } from './models/BaseResponse_long_.ts';
export type { BaseResponse_Map_string_object_ } from './models/BaseResponse_Map_string_object_.ts';
export type { BaseResponse_Page_AiAvatarVO_ } from './models/BaseResponse_Page_AiAvatarVO_.ts';
export type { BaseResponse_Page_Announcement_ } from './models/BaseResponse_Page_Announcement_.ts';
export type { BaseResponse_Page_AnnouncementVO_ } from './models/BaseResponse_Page_AnnouncementVO_.ts';
export type { BaseResponse_Page_ChatMessageVO_ } from './models/BaseResponse_Page_ChatMessageVO_.ts';
export type { BaseResponse_Page_CourseChapter_ } from './models/BaseResponse_Page_CourseChapter_.ts';
export type { BaseResponse_Page_CourseMaterial_ } from './models/BaseResponse_Page_CourseMaterial_.ts';
export type { BaseResponse_Page_CourseReviewVO_ } from './models/BaseResponse_Page_CourseReviewVO_.ts';
export type { BaseResponse_Page_CourseSection_ } from './models/BaseResponse_Page_CourseSection_.ts';
export type { BaseResponse_Page_CourseVO_ } from './models/BaseResponse_Page_CourseVO_.ts';
export type { BaseResponse_Page_DailyArticle_ } from './models/BaseResponse_Page_DailyArticle_.ts';
export type { BaseResponse_Page_DailyArticleVO_ } from './models/BaseResponse_Page_DailyArticleVO_.ts';
export type { BaseResponse_Page_DailyWord_ } from './models/BaseResponse_Page_DailyWord_.ts';
export type { BaseResponse_Page_DailyWordVO_ } from './models/BaseResponse_Page_DailyWordVO_.ts';
export type { BaseResponse_Page_Post_ } from './models/BaseResponse_Page_Post_.ts';
export type { BaseResponse_Page_PostVO_ } from './models/BaseResponse_Page_PostVO_.ts';
export type { BaseResponse_Page_Teacher_ } from './models/BaseResponse_Page_Teacher_.ts';
export type { BaseResponse_Page_TeacherVO_ } from './models/BaseResponse_Page_TeacherVO_.ts';
export type { BaseResponse_Page_User_ } from './models/BaseResponse_Page_User_.ts';
export type { BaseResponse_Page_UserAiAvatarVO_ } from './models/BaseResponse_Page_UserAiAvatarVO_.ts';
export type { BaseResponse_Page_UserLearningRecordVO_ } from './models/BaseResponse_Page_UserLearningRecordVO_.ts';
export type { BaseResponse_Page_UserLevel_ } from './models/BaseResponse_Page_UserLevel_.ts';
export type { BaseResponse_Page_UserLevelVO_ } from './models/BaseResponse_Page_UserLevelVO_.ts';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_.ts';
export type { BaseResponse_PostVO_ } from './models/BaseResponse_PostVO_.ts';
export type { BaseResponse_string_ } from './models/BaseResponse_string_.ts';
export type { BaseResponse_Teacher_ } from './models/BaseResponse_Teacher_.ts';
export type { BaseResponse_TeacherVO_ } from './models/BaseResponse_TeacherVO_.ts';
export type { BaseResponse_UploadFileResponse_ } from './models/BaseResponse_UploadFileResponse_.ts';
export type { BaseResponse_User_ } from './models/BaseResponse_User_.ts';
export type { BaseResponse_UserAiAvatarVO_ } from './models/BaseResponse_UserAiAvatarVO_.ts';
export type { BaseResponse_UserDailyWord_ } from './models/BaseResponse_UserDailyWord_.ts';
export type { BaseResponse_UserLearningRecordVO_ } from './models/BaseResponse_UserLearningRecordVO_.ts';
export type { BaseResponse_UserLearningStats_ } from './models/BaseResponse_UserLearningStats_.ts';
export type { BaseResponse_UserLevel_ } from './models/BaseResponse_UserLevel_.ts';
export type { BaseResponse_UserLevelVO_ } from './models/BaseResponse_UserLevelVO_.ts';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_.ts';
export type { ChatMessageAddRequest } from './models/ChatMessageAddRequest.ts';
export type { ChatMessageVO } from './models/ChatMessageVO.ts';
export type { ChatSessionUpdateRequest } from './models/ChatSessionUpdateRequest.ts';
export type { ChatSessionVO } from './models/ChatSessionVO.ts';
export type { Course } from './models/Course.ts';
export type { CourseAddRequest } from './models/CourseAddRequest.ts';
export type { CourseCategory } from './models/CourseCategory.ts';
export type { CourseChapter } from './models/CourseChapter.ts';
export type { CourseFavourAddRequest } from './models/CourseFavourAddRequest.ts';
export type { CourseMaterial } from './models/CourseMaterial.ts';
export type { CourseReview } from './models/CourseReview.ts';
export type { CourseReviewVO } from './models/CourseReviewVO.ts';
export type { CourseSection } from './models/CourseSection.ts';
export type { CourseUpdateRequest } from './models/CourseUpdateRequest.ts';
export type { CourseVO } from './models/CourseVO.ts';
export type { DailyArticle } from './models/DailyArticle.ts';
export type { DailyArticleAddRequest } from './models/DailyArticleAddRequest.ts';
export type { DailyArticleQueryRequest } from './models/DailyArticleQueryRequest.ts';
export type { DailyArticleUpdateRequest } from './models/DailyArticleUpdateRequest.ts';
export type { DailyArticleVO } from './models/DailyArticleVO.ts';
export type { DailyWord } from './models/DailyWord.ts';
export type { DailyWordAddRequest } from './models/DailyWordAddRequest.ts';
export type { DailyWordQueryRequest } from './models/DailyWordQueryRequest.ts';
export type { DailyWordUpdateRequest } from './models/DailyWordUpdateRequest.ts';
export type { DailyWordVO } from './models/DailyWordVO.ts';
export type { DeleteRequest } from './models/DeleteRequest.ts';
export type { DeleteRequest_1 } from './models/DeleteRequest_1.ts';
export type { LoginUserVO } from './models/LoginUserVO.ts';
export type { Map_string_object_ } from './models/Map_string_object_.ts';
export type { Map_string_object__1 } from './models/Map_string_object__1.ts';
export type { Map_string_object__2 } from './models/Map_string_object__2.ts';
export type { OrderItem } from './models/OrderItem.ts';
export type { Page_AiAvatarVO_ } from './models/Page_AiAvatarVO_.ts';
export type { Page_Announcement_ } from './models/Page_Announcement_.ts';
export type { Page_AnnouncementVO_ } from './models/Page_AnnouncementVO_.ts';
export type { Page_ChatMessageVO_ } from './models/Page_ChatMessageVO_.ts';
export type { Page_CourseChapter_ } from './models/Page_CourseChapter_.ts';
export type { Page_CourseMaterial_ } from './models/Page_CourseMaterial_.ts';
export type { Page_CourseReviewVO_ } from './models/Page_CourseReviewVO_.ts';
export type { Page_CourseSection_ } from './models/Page_CourseSection_.ts';
export type { Page_CourseVO_ } from './models/Page_CourseVO_.ts';
export type { Page_DailyArticle_ } from './models/Page_DailyArticle_.ts';
export type { Page_DailyArticleVO_ } from './models/Page_DailyArticleVO_.ts';
export type { Page_DailyWord_ } from './models/Page_DailyWord_.ts';
export type { Page_DailyWordVO_ } from './models/Page_DailyWordVO_.ts';
export type { Page_Post_ } from './models/Page_Post_.ts';
export type { Page_PostVO_ } from './models/Page_PostVO_.ts';
export type { Page_Teacher_ } from './models/Page_Teacher_.ts';
export type { Page_TeacherVO_ } from './models/Page_TeacherVO_.ts';
export type { Page_User_ } from './models/Page_User_.ts';
export type { Page_UserAiAvatarVO_ } from './models/Page_UserAiAvatarVO_.ts';
export type { Page_UserLearningRecordVO_ } from './models/Page_UserLearningRecordVO_.ts';
export type { Page_UserLevel_ } from './models/Page_UserLevel_.ts';
export type { Page_UserLevelVO_ } from './models/Page_UserLevelVO_.ts';
export type { Page_UserVO_ } from './models/Page_UserVO_.ts';
export type { Post } from './models/Post.ts';
export type { PostAddRequest } from './models/PostAddRequest.ts';
export type { PostEditRequest } from './models/PostEditRequest.ts';
export type { PostFavourAddRequest } from './models/PostFavourAddRequest.ts';
export type { PostFavourQueryRequest } from './models/PostFavourQueryRequest.ts';
export type { PostQueryRequest } from './models/PostQueryRequest.ts';
export type { PostThumbAddRequest } from './models/PostThumbAddRequest.ts';
export type { PostUpdateRequest } from './models/PostUpdateRequest.ts';
export type { PostVO } from './models/PostVO.ts';
export type { SseEmitter } from './models/SseEmitter.ts';
export type { StopStreamingRequest } from './models/StopStreamingRequest.ts';
export type { Teacher } from './models/Teacher.ts';
export type { TeacherAddRequest } from './models/TeacherAddRequest.ts';
export type { TeacherQueryRequest } from './models/TeacherQueryRequest.ts';
export type { TeacherUpdateRequest } from './models/TeacherUpdateRequest.ts';
export type { TeacherVO } from './models/TeacherVO.ts';
export type { TextToAudioRequest } from './models/TextToAudioRequest.ts';
export type { UploadFileResponse } from './models/UploadFileResponse.ts';
export type { User } from './models/User.ts';
export type { UserAddRequest } from './models/UserAddRequest.ts';
export type { UserAiAvatarAddRequest } from './models/UserAiAvatarAddRequest.ts';
export type { UserAiAvatarUpdateRequest } from './models/UserAiAvatarUpdateRequest.ts';
export type { UserAiAvatarVO } from './models/UserAiAvatarVO.ts';
export type { UserDailyWord } from './models/UserDailyWord.ts';
export type { UserLearningRecordAddRequest } from './models/UserLearningRecordAddRequest.ts';
export type { UserLearningRecordQueryRequest } from './models/UserLearningRecordQueryRequest.ts';
export type { UserLearningRecordUpdateRequest } from './models/UserLearningRecordUpdateRequest.ts';
export type { UserLearningRecordVO } from './models/UserLearningRecordVO.ts';
export type { UserLearningStats } from './models/UserLearningStats.ts';
export type { UserLevel } from './models/UserLevel.ts';
export type { UserLevelAddRequest } from './models/UserLevelAddRequest.ts';
export type { UserLevelQueryRequest } from './models/UserLevelQueryRequest.ts';
export type { UserLevelUpdateRequest } from './models/UserLevelUpdateRequest.ts';
export type { UserLevelVO } from './models/UserLevelVO.ts';
export type { UserLoginByPhoneRequest } from './models/UserLoginByPhoneRequest.ts';
export type { UserLoginRequest } from './models/UserLoginRequest.ts';
export type { UserQueryRequest } from './models/UserQueryRequest.ts';
export type { UserRegisterByPhoneRequest } from './models/UserRegisterByPhoneRequest.ts';
export type { UserRegisterRequest } from './models/UserRegisterRequest.ts';
export type { UserUpdateMyRequest } from './models/UserUpdateMyRequest.ts';
export type { UserUpdateRequest } from './models/UserUpdateRequest.ts';
export type { UserVO } from './models/UserVO.ts';

export { AiAvatarChatControllerService } from './services/AiAvatarChatControllerService.ts';
export { AiAvatarControllerService } from './services/AiAvatarControllerService.ts';
export { AnnouncementControllerService } from './services/AnnouncementControllerService.ts';
export { CourseCategoryControllerService } from './services/CourseCategoryControllerService.ts';
export { CourseChapterControllerService } from './services/CourseChapterControllerService.ts';
export { CourseControllerService } from './services/CourseControllerService.ts';
export { CourseFavouriteControllerService } from './services/CourseFavouriteControllerService.ts';
export { CourseMaterialControllerService } from './services/CourseMaterialControllerService.ts';
export { CourseReviewControllerService } from './services/CourseReviewControllerService.ts';
export { CourseSectionControllerService } from './services/CourseSectionControllerService.ts';
export { DailyArticleControllerService } from './services/DailyArticleControllerService.ts';
export { DailyArticleFavourControllerService } from './services/DailyArticleFavourControllerService.ts';
export { DailyArticleThumbControllerService } from './services/DailyArticleThumbControllerService.ts';
export { DailyWordControllerService } from './services/DailyWordControllerService.ts';
export { DailyWordFavourControllerService } from './services/DailyWordFavourControllerService.ts';
export { DailyWordLearningControllerService } from './services/DailyWordLearningControllerService.ts';
export { DailyWordThumbControllerService } from './services/DailyWordThumbControllerService.ts';
export { FileControllerService } from './services/FileControllerService.ts';
export { PostControllerService } from './services/PostControllerService.ts';
export { PostFavourControllerService } from './services/PostFavourControllerService.ts';
export { PostThumbControllerService } from './services/PostThumbControllerService.ts';
export { TeacherControllerService } from './services/TeacherControllerService.ts';
export { UserAiAvatarControllerService } from './services/UserAiAvatarControllerService.ts';
export { UserControllerService } from './services/UserControllerService.ts';
export { UserLearningRecordControllerService } from './services/UserLearningRecordControllerService.ts';
export { UserLearningStatsControllerService } from './services/UserLearningStatsControllerService.ts';
export { UserLevelControllerService } from './services/UserLevelControllerService.ts';
export { WxMpControllerService } from './services/WxMpControllerService.ts';
